// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServer.Data;

#nullable disable

namespace SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreEntities.Model.Attachment", b =>
                {
                    b.Property<string>("AttachmentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AttachmentId");

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CommentId");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAdded");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileName");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MimeType");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TaskId");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UploadedBy");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CommentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CoreEntities.Model.ChecklistFL", b =>
                {
                    b.Property<string>("ChecklistId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ChecklistId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TaskId");

                    b.HasKey("ChecklistId");

                    b.HasIndex("TaskId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("CoreEntities.Model.ChecklistItemFL", b =>
                {
                    b.Property<string>("ChecklistItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ChecklistItemId");

                    b.Property<string>("ChecklistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ChecklistId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<bool?>("IsResolved")
                        .HasColumnType("bit")
                        .HasColumnName("IsResolved");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("OrderIndex");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResolvedAt");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ResolvedBy");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("CoreEntities.Model.Comment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CommentId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CommentText");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<bool?>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("IsEdited");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TaskId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserId");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CoreEntities.Model.CustomFieldFL", b =>
                {
                    b.Property<string>("FieldId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FieldId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<string>("FieldType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FieldType");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Options");

                    b.HasKey("FieldId");

                    b.ToTable("CustomFields");
                });

            modelBuilder.Entity("CoreEntities.Model.Folder", b =>
                {
                    b.Property<string>("FolderId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FolderId");

                    b.Property<bool?>("Archived")
                        .HasColumnType("bit")
                        .HasColumnName("Archived");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("bit")
                        .HasColumnName("Hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("SpaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SpaceId");

                    b.HasKey("FolderId");

                    b.HasIndex("SpaceId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("CoreEntities.Model.GoalFL", b =>
                {
                    b.Property<string>("GoalId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("GoalId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<double?>("Progress")
                        .HasColumnType("float")
                        .HasColumnName("Progress");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TeamId");

                    b.HasKey("GoalId");

                    b.HasIndex("TeamId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("CoreEntities.Model.List", b =>
                {
                    b.Property<string>("ListId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ListId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<string>("FolderId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FolderId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Priority");

                    b.Property<string>("SpaceId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SpaceId");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.HasKey("ListId");

                    b.HasIndex("FolderId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("CoreEntities.Model.Space", b =>
                {
                    b.Property<string>("SpaceId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SpaceId");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<bool?>("IsPrivate")
                        .HasColumnType("bit")
                        .HasColumnName("IsPrivate");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Settings");

                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TeamId");

                    b.HasKey("SpaceId");

                    b.HasIndex("TeamId");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("CoreEntities.Model.Tag", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TagId");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskAssignee", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TaskId");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("AssignedAt");

                    b.HasKey("TaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskAssignees");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskCustomFieldValueFL", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("FieldId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("TaskId", "FieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("TaskCustomFieldValues");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskFL", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatorId");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateClosed");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("IsArchived");

                    b.Property<string>("ListId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ListId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("ParentTaskId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ParentTaskId");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Priority");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<long?>("TimeEstimate")
                        .HasColumnType("bigint")
                        .HasColumnName("TimeEstimate");

                    b.Property<long?>("TimeSpent")
                        .HasColumnType("bigint")
                        .HasColumnName("TimeSpent");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskTag", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TaskId", "TagId");

                    b.ToTable("TaskTags");
                });

            modelBuilder.Entity("CoreEntities.Model.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TeamId");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Avatar");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CoreEntities.Model.TeamMember", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TeamId");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("DateJoined")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateJoined");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("CoreEntities.Model.TimeEntryFL", b =>
                {
                    b.Property<string>("TimeEntryId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TimeEntryId");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("DurationMilliseconds");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndTime");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartTime");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TaskId");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("TimeEntryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("CoreEntities.Model.UserFL", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Color");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreated");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateUpdated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PasswordSalt");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProfilePicture");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Timezone");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreEntities.Model.Attachment", b =>
                {
                    b.HasOne("CoreEntities.Model.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("CoreEntities.Model.TaskFL", "Task")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId");

                    b.Navigation("Comment");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CoreEntities.Model.ChecklistFL", b =>
                {
                    b.HasOne("CoreEntities.Model.TaskFL", "Task")
                        .WithMany("Checklists")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CoreEntities.Model.ChecklistItemFL", b =>
                {
                    b.HasOne("CoreEntities.Model.ChecklistFL", "Checklist")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreEntities.Model.UserFL", "User")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Checklist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreEntities.Model.Comment", b =>
                {
                    b.HasOne("CoreEntities.Model.TaskFL", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CoreEntities.Model.Folder", b =>
                {
                    b.HasOne("CoreEntities.Model.Space", null)
                        .WithMany("Folders")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreEntities.Model.GoalFL", b =>
                {
                    b.HasOne("CoreEntities.Model.Team", "Teams")
                        .WithMany("Goals")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("CoreEntities.Model.List", b =>
                {
                    b.HasOne("CoreEntities.Model.Folder", null)
                        .WithMany("Lists")
                        .HasForeignKey("FolderId");
                });

            modelBuilder.Entity("CoreEntities.Model.Space", b =>
                {
                    b.HasOne("CoreEntities.Model.Team", "Teams")
                        .WithMany("Spaces")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskAssignee", b =>
                {
                    b.HasOne("CoreEntities.Model.TaskFL", "Tasks")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreEntities.Model.UserFL", "UserFLs")
                        .WithMany("TaskAssignees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tasks");

                    b.Navigation("UserFLs");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskCustomFieldValueFL", b =>
                {
                    b.HasOne("CoreEntities.Model.CustomFieldFL", "CustomField")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreEntities.Model.TaskFL", "Task")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskFL", b =>
                {
                    b.HasOne("CoreEntities.Model.List", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId");

                    b.Navigation("List");
                });

            modelBuilder.Entity("CoreEntities.Model.TeamMember", b =>
                {
                    b.HasOne("CoreEntities.Model.Team", "Teams")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreEntities.Model.UserFL", "UserFLs")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");

                    b.Navigation("UserFLs");
                });

            modelBuilder.Entity("CoreEntities.Model.TimeEntryFL", b =>
                {
                    b.HasOne("CoreEntities.Model.TaskFL", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CoreEntities.Model.UserFL", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreEntities.Model.ChecklistFL", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("CoreEntities.Model.CustomFieldFL", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("CoreEntities.Model.Folder", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("CoreEntities.Model.List", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CoreEntities.Model.Space", b =>
                {
                    b.Navigation("Folders");
                });

            modelBuilder.Entity("CoreEntities.Model.TaskFL", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Checklists");

                    b.Navigation("Comments");

                    b.Navigation("CustomFieldValues");

                    b.Navigation("TaskAssignees");
                });

            modelBuilder.Entity("CoreEntities.Model.Team", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Spaces");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("CoreEntities.Model.UserFL", b =>
                {
                    b.Navigation("TaskAssignees");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
